import { useState } from 'react';
import { supabase } from '@/services/supabaseClient';
import { X, Loader2 } from 'lucide-react';
import type { Job, JobStatus, Vehicle, User } from '@/types';

interface JobModalProps {
  job: Job | null;
  orgId: string;
  userId: string;
  vehicles: Vehicle[];
  drivers: User[];
  onClose: () => void;
  onSaved: () => void;
}

const STATUS_OPTIONS: { value: JobStatus; label: string }[] = [
  { value: 'pending',   label: 'Pending' },
  { value: 'active',    label: 'Active' },
  { value: 'completed', label: 'Completed' },
  { value: 'cancelled', label: 'Cancelled' },
];

export function JobModal({ job, orgId, userId, vehicles, drivers, onClose, onSaved }: JobModalProps) {
  const isEditing = !!job;

  const [title,       setTitle]       = useState(job?.title ?? '');
  const [description, setDescription] = useState(job?.description ?? '');
  const [siteAddress, setSiteAddress] = useState(job?.site_address ?? '');
  const [vehicleId,   setVehicleId]   = useState(job?.vehicle_id ?? '');
  const [driverId,    setDriverId]    = useState(job?.driver_id ?? '');
  const [status,      setStatus]      = useState<JobStatus>(job?.status ?? 'pending');
  const [saving,      setSaving]      = useState(false);
  const [error,       setError]       = useState<string | null>(null);

  const activeVehicles = vehicles.filter((v) => v.status === 'active');
  const activeDrivers  = drivers.filter((u) => u.roles.includes('driver') && u.is_active);

  const handleSave = async () => {
    if (!title.trim()) {
      setError('Title is required.');
      return;
    }
    setSaving(true);
    setError(null);

    try {
      if (isEditing) {
        const prevStatus = job.status;
        const { error: updateError } = await supabase
          .from('jobs')
          .update({
            title:        title.trim(),
            description:  description.trim() || null,
            site_address: siteAddress.trim() || null,
            vehicle_id:   vehicleId || null,
            driver_id:    driverId  || null,
            status,
          })
          .eq('id', job.id);

        if (updateError) throw updateError;

        // Record status change in history if it changed
        if (status !== prevStatus) {
          await supabase.from('job_status_history').insert({
            job_id:     job.id,
            status,
            changed_by: userId,
          });
        }
      } else {
        // reference and job_code are generated by DB trigger — do not supply them
        const { error: insertError } = await supabase
          .from('jobs')
          .insert({
            org_id:       orgId,
            created_by:   userId,
            title:        title.trim(),
            description:  description.trim() || null,
            site_address: siteAddress.trim() || null,
            vehicle_id:   vehicleId || null,
            driver_id:    driverId  || null,
            status:       'pending',
          });

        if (insertError) throw insertError;
      }

      onSaved();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to save job.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-xl shadow-xl w-full max-w-lg max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200">
          <h2 className="text-lg font-bold text-slate-900">
            {isEditing ? `Edit Job — ${job.reference}` : 'New Job'}
          </h2>
          <button onClick={onClose} className="p-1 text-slate-400 hover:text-slate-600">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-6 py-4 space-y-4">
          {error && (
            <div className="p-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700">
              {error}
            </div>
          )}

          {isEditing && (
            <div className="flex gap-3">
              <div className="flex-1">
                <p className="text-xs font-medium text-slate-500 mb-1">Reference</p>
                <p className="font-mono font-bold text-slate-900">{job.reference}</p>
              </div>
              <div className="flex-1">
                <p className="text-xs font-medium text-slate-500 mb-1">Job Code</p>
                <p className="font-mono font-bold text-slate-900">{job.job_code}</p>
              </div>
            </div>
          )}

          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">
              Title <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g. Excavation waste removal — Site A"
              className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-orange-500 focus:border-transparent outline-none"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Site Address</label>
            <input
              type="text"
              value={siteAddress}
              onChange={(e) => setSiteAddress(e.target.value)}
              placeholder="e.g. 12 Industrial Rd, Birmingham"
              className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-orange-500 focus:border-transparent outline-none"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Description</label>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              rows={3}
              placeholder="Optional notes about the job"
              className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-orange-500 focus:border-transparent outline-none resize-none"
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Vehicle</label>
              <select
                value={vehicleId}
                onChange={(e) => setVehicleId(e.target.value)}
                className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-orange-500 focus:border-transparent outline-none"
              >
                <option value="">— Not assigned —</option>
                {activeVehicles.map((v) => (
                  <option key={v.id} value={v.id}>{v.registration}</option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Driver</label>
              <select
                value={driverId}
                onChange={(e) => setDriverId(e.target.value)}
                className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-orange-500 focus:border-transparent outline-none"
              >
                <option value="">— Not assigned —</option>
                {activeDrivers.map((u) => (
                  <option key={u.id} value={u.id}>{u.name}</option>
                ))}
              </select>
            </div>
          </div>

          {isEditing && (
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Status</label>
              <select
                value={status}
                onChange={(e) => setStatus(e.target.value as JobStatus)}
                className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-orange-500 focus:border-transparent outline-none"
              >
                {STATUS_OPTIONS.map((s) => (
                  <option key={s.value} value={s.value}>{s.label}</option>
                ))}
              </select>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex gap-3 px-6 py-4 border-t border-slate-200">
          <button
            onClick={onClose}
            className="flex-1 py-2 border border-slate-300 text-slate-700 rounded-lg hover:bg-slate-50 text-sm font-medium"
          >
            Cancel
          </button>
          <button
            onClick={handleSave}
            disabled={saving || !title.trim()}
            className="flex-1 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 disabled:opacity-50 disabled:cursor-not-allowed text-sm font-bold flex items-center justify-center gap-2"
          >
            {saving && <Loader2 className="w-4 h-4 animate-spin" />}
            {isEditing ? 'Save Changes' : 'Create Job'}
          </button>
        </div>
      </div>
    </div>
  );
}
