-- ============================================================================
-- Migration: 014_jobs
-- Job management for Tier 2 (Manage) operators
-- ============================================================================

-- Counter on organisations — atomically incremented each time a job is created
ALTER TABLE organisations
  ADD COLUMN IF NOT EXISTS next_job_seq integer NOT NULL DEFAULT 0;

-- ============================================================================
-- Helper: integer sequence → 3-letter job code (1=AAA, 2=AAB, … 17576=ZZZ)
-- Used as the job-level identifier in invoice references: AAA-INS-0001
-- ============================================================================
CREATE OR REPLACE FUNCTION seq_to_job_code(seq integer) RETURNS text
LANGUAGE plpgsql IMMUTABLE
AS $$
DECLARE
  n integer := seq - 1;
BEGIN
  IF seq < 1 OR seq > 17576 THEN
    RAISE EXCEPTION 'seq_to_job_code: % is out of range (1–17576)', seq;
  END IF;
  RETURN chr(65 + (n / 676)) || chr(65 + ((n / 26) % 26)) || chr(65 + (n % 26));
END;
$$;

-- ============================================================================
-- jobs
-- ============================================================================
CREATE TABLE IF NOT EXISTS jobs (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id     uuid        NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  vehicle_id uuid        REFERENCES vehicles(id) ON DELETE SET NULL,
  driver_id  uuid        REFERENCES users(id) ON DELETE SET NULL,
  created_by uuid        NOT NULL REFERENCES users(id),

  -- Generated by trigger on INSERT — do not supply from the application
  reference  text        NOT NULL,   -- e.g. JOB-0001
  job_code   text        NOT NULL,   -- e.g. AAA  (used in invoice refs)

  title        text NOT NULL,
  description  text,
  site_address text,

  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'active', 'completed', 'cancelled')),

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  UNIQUE (org_id, reference),
  UNIQUE (org_id, job_code)
);

-- Atomically increment org counter and derive reference + job_code
CREATE OR REPLACE FUNCTION generate_job_identifiers()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  new_seq integer;
BEGIN
  UPDATE organisations
    SET next_job_seq = next_job_seq + 1
    WHERE id = NEW.org_id
    RETURNING next_job_seq INTO new_seq;

  NEW.reference := 'JOB-' || lpad(new_seq::text, 4, '0');
  NEW.job_code  := seq_to_job_code(new_seq);
  RETURN NEW;
END;
$$;

CREATE TRIGGER set_job_identifiers
  BEFORE INSERT ON jobs
  FOR EACH ROW
  EXECUTE FUNCTION generate_job_identifiers();

-- Keep updated_at current on every update
CREATE OR REPLACE FUNCTION touch_job_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER jobs_updated_at
  BEFORE UPDATE ON jobs
  FOR EACH ROW
  EXECUTE FUNCTION touch_job_updated_at();

-- ============================================================================
-- job_status_history — immutable audit trail (one row per status change)
-- ============================================================================
CREATE TABLE IF NOT EXISTS job_status_history (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id     uuid        NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  status     text        NOT NULL,
  note       text,
  changed_by uuid        NOT NULL REFERENCES users(id),
  changed_at timestamptz NOT NULL DEFAULT now()
);

-- Auto-record the initial status when a job is created
CREATE OR REPLACE FUNCTION record_initial_job_status()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO job_status_history (job_id, status, changed_by)
  VALUES (NEW.id, NEW.status, NEW.created_by);
  RETURN NEW;
END;
$$;

CREATE TRIGGER jobs_initial_status
  AFTER INSERT ON jobs
  FOR EACH ROW
  EXECUTE FUNCTION record_initial_job_status();

-- ============================================================================
-- Indexes
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_jobs_org_id      ON jobs (org_id);
CREATE INDEX IF NOT EXISTS idx_jobs_driver_id   ON jobs (driver_id);
CREATE INDEX IF NOT EXISTS idx_jobs_org_status  ON jobs (org_id, status);
CREATE INDEX IF NOT EXISTS idx_jsh_job_id       ON job_status_history (job_id);

-- ============================================================================
-- Row Level Security
-- ============================================================================
ALTER TABLE jobs             ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_status_history ENABLE ROW LEVEL SECURITY;

-- Managers: full access to jobs in their org
CREATE POLICY "managers_all_jobs" ON jobs
  FOR ALL TO authenticated
  USING    (org_id = auth_user_org_id() AND auth_user_has_role('manager'))
  WITH CHECK (org_id = auth_user_org_id() AND auth_user_has_role('manager'));

-- Drivers: read jobs assigned to them
CREATE POLICY "drivers_read_own_jobs" ON jobs
  FOR SELECT TO authenticated
  USING (driver_id = auth_user_id());

-- Managers: full access to status history for jobs in their org
CREATE POLICY "managers_all_job_history" ON job_status_history
  FOR ALL TO authenticated
  USING (
    job_id IN (
      SELECT id FROM jobs WHERE org_id = auth_user_org_id()
    )
    AND auth_user_has_role('manager')
  )
  WITH CHECK (
    job_id IN (
      SELECT id FROM jobs WHERE org_id = auth_user_org_id()
    )
    AND auth_user_has_role('manager')
  );

-- Drivers: read status history for their assigned jobs
CREATE POLICY "drivers_read_own_job_history" ON job_status_history
  FOR SELECT TO authenticated
  USING (
    job_id IN (
      SELECT id FROM jobs WHERE driver_id = auth_user_id()
    )
  );
