-- ============================================================================
-- Migration: 021_invoices
-- Invoice management for Tier 3 (Control) operators
-- ============================================================================

-- Counter on organisations for invoice sequences
ALTER TABLE organisations
  ADD COLUMN IF NOT EXISTS next_invoice_seq integer NOT NULL DEFAULT 0;

-- ============================================================================
-- invoices
-- ============================================================================
CREATE TABLE IF NOT EXISTS invoices (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id       uuid        NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  created_by   uuid        NOT NULL REFERENCES users(id),
  job_id       uuid        REFERENCES jobs(id) ON DELETE SET NULL,

  -- Generated by trigger on INSERT — do not supply from application
  number       text        NOT NULL,    -- e.g. INV-0001

  -- Client details
  client_name    text NOT NULL,
  client_address text,
  client_email   text,

  -- Dates
  issue_date   date NOT NULL DEFAULT CURRENT_DATE,
  due_date     date,

  -- Financials
  vat_enabled  boolean NOT NULL DEFAULT true,
  total_net    numeric(10,2) NOT NULL DEFAULT 0,
  total_vat    numeric(10,2) NOT NULL DEFAULT 0,
  total_gross  numeric(10,2) NOT NULL DEFAULT 0,

  -- Notes
  notes        text,

  -- Status lifecycle: draft → sent → paid (or void at any point)
  status       text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'sent', 'paid', 'void')),

  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),

  UNIQUE (org_id, number)
);

-- Atomically increment org counter and set invoice number
CREATE OR REPLACE FUNCTION generate_invoice_number()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  new_seq integer;
BEGIN
  UPDATE organisations
    SET next_invoice_seq = next_invoice_seq + 1
    WHERE id = NEW.org_id
    RETURNING next_invoice_seq INTO new_seq;

  NEW.number := 'INV-' || lpad(new_seq::text, 4, '0');
  RETURN NEW;
END;
$$;

CREATE TRIGGER set_invoice_number
  BEFORE INSERT ON invoices
  FOR EACH ROW
  EXECUTE FUNCTION generate_invoice_number();

CREATE OR REPLACE FUNCTION touch_invoice_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER invoices_updated_at
  BEFORE UPDATE ON invoices
  FOR EACH ROW
  EXECUTE FUNCTION touch_invoice_updated_at();

-- ============================================================================
-- invoice_items
-- ============================================================================
CREATE TABLE IF NOT EXISTS invoice_items (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id  uuid        NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  sort_order  integer     NOT NULL DEFAULT 0,
  description text        NOT NULL,
  quantity    numeric(10,3) NOT NULL DEFAULT 1,
  unit_price  numeric(10,2) NOT NULL DEFAULT 0,
  total       numeric(10,2) NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- RLS
-- ============================================================================
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_items ENABLE ROW LEVEL SECURITY;

-- Managers in the org can read/write invoices
CREATE POLICY "Managers manage org invoices"
  ON invoices
  FOR ALL
  USING (
    org_id IN (
      SELECT org_id FROM users
      WHERE auth_user_id = auth.uid()
        AND 'manager' = ANY(roles)
        AND is_active = true
    )
  )
  WITH CHECK (
    org_id IN (
      SELECT org_id FROM users
      WHERE auth_user_id = auth.uid()
        AND 'manager' = ANY(roles)
        AND is_active = true
    )
  );

CREATE POLICY "Managers manage org invoice items"
  ON invoice_items
  FOR ALL
  USING (
    invoice_id IN (
      SELECT id FROM invoices WHERE org_id IN (
        SELECT org_id FROM users
        WHERE auth_user_id = auth.uid()
          AND 'manager' = ANY(roles)
          AND is_active = true
      )
    )
  )
  WITH CHECK (
    invoice_id IN (
      SELECT id FROM invoices WHERE org_id IN (
        SELECT org_id FROM users
        WHERE auth_user_id = auth.uid()
          AND 'manager' = ANY(roles)
          AND is_active = true
      )
    )
  );

-- ============================================================================
-- Public RPC — no auth required, used for shareable invoice page
-- ============================================================================
CREATE OR REPLACE FUNCTION get_invoice_public(p_number text)
RETURNS json
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT json_build_object(
    'invoice', row_to_json(i),
    'items', (
      SELECT json_agg(row_to_json(ii) ORDER BY ii.sort_order)
      FROM invoice_items ii
      WHERE ii.invoice_id = i.id
    ),
    'org_name', o.name
  )
  FROM invoices i
  JOIN organisations o ON o.id = i.org_id
  WHERE i.number = upper(p_number)
    AND i.status != 'void';
$$;
